skaterapp/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemUpdateView,
    ItemDetailView,
    ItemCreateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

skaterapp/restaurants/urls.py
from django.conf.urls import url

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
]

skaterapp/skaterapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView

from profiles.views import ProfileFollowToggle


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^anggaran/', include('anggaran.urls', namespace='anggaran')),
]

skaterapp/restaurants/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query):
        if query :
            query = query.strip()
            return self.filter(
                Q(location__icontains=query)|
                Q(category__icontains=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
    
            ).distinct()
        return self


class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class RestaurantLocation(models.Model) :
    owner           = models.ForeignKey(User)  # django models unleashed joincfe
    name            = models.CharField(max_length = 120)
    location        = models.CharField(max_length = 120, null = True, blank = True)
    category        = models.CharField(max_length = 120, null = True, blank = True, validators=[validate_category])
    timestamp       = models.DateTimeField(auto_now_add = True)
    updated         = models.DateTimeField(auto_now=True)
    slug            = models.SlugField(unique=True, null=True, blank=True)

    objects = RestaurantLocationManager() # add Model.objects.all()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    def get_absolute_url_update(self):
        return reverse('restaurants:edit', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def restaurantLocationPreSaveReceiver(sender, instance, *args, **kwargs) :
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def restaurantLocationPostSaveReceiver(sender, instance, created, *args, **kwargs) :
#     print('saved')
#     print(instance.timestamp)
#     if not instance.slug:
#         instance.slug = unique_slug_generator(instance)
#         instance.save()


pre_save.connect(restaurantLocationPreSaveReceiver, sender=RestaurantLocation)

# post_save.connect(restaurantLocationPostSaveReceiver, sender=RestaurantLocation)

skaterapp/restaurants/forms.py
from django import forms
from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form) :
    name            = forms.CharField()
    location        = forms.CharField(required=False)
    category        = forms.CharField(required=False)

class RestaurantLocationCreateForm(forms.ModelForm) :
    # email           = forms.EmailField()
    #category          = forms.CharField( required=False, validators=[validate_category])
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
        ]
    #
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Your name's not Hello")
        return name

skaterapp/restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.views import View
from django.views.generic import TemplateView, DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from .models import RestaurantLocation
from .forms import RestaurantLocationCreateForm

class RestaurantListView(LoginRequiredMixin, ListView) :
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(DetailView) :
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView) :
    form_class = RestaurantLocationCreateForm
    template_name = 'form.html'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView) :
    form_class = RestaurantLocationCreateForm
    template_name = 'restaurants/detail-update.html'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Edit {}'.format(self.get_object().name)
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

skaterapp/restaurants/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

skaterapp/restaurants/templates/snippets/form_snippet.html
{% if form.errors.non_field_errors %}
    {{ form.errors.non_field_errors }}
{% endif %}
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

skaterapp/restaurants/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

skaterapp/restaurants/templates/snippets/nav.html
<h1> SkaterAPP </h1>
<p>
    |
    <a href = '{% url "home" %}'>Home</a> |
{#    <a href = '/contact_view'>Contact View</a> |#}
{#    <a href = '/contact_template_view'>Contact Template View</a> |#}
    <a href = '{% url "about"%}'>About</a> |
    <a href = '{% url "contact" %}'>Contact</a> |

    {% if request.user.is_authenticated %}
        <a href = '{% url "restaurants:list" %}'>Restaurants</a> |
        <a href = '{% url "menus:list" %}'>Menu Items</a> |
    {% endif %}
</p>

skaterapp/restaurants/templates/snippets/sidebar.html
<ul>
    <li> list xx</li>
    <li> list x1</li>
    <li> list x2</li>
    <li> list x3</li>
    <li> list x4</li>

</ul>