skaterapp/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemUpdateView,
    ItemDetailView,
    ItemCreateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

skaterapp/skaterapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView

from profiles.views import ProfileFollowToggle


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^anggaran/', include('anggaran.urls', namespace='anggaran')),
]

skaterapp/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation

# Create your models here.
class Item(models.Model):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)
    name            = models.CharField(max_length=120)
    contents        = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    excludes        = models.TextField(blank=True, null=True, help_text='Separated each item by comma')
    public          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk':self.pk})

    def get_absolute_url_update(self):
        return reverse('menus:update', kwargs={'pk':self.pk})

    class Meta:
        # use to ordering data as default
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

    def __str__(self):
        return '{} - {}'.format(self.restaurant, self.name)

skaterapp/menus/forms.py
from django import forms
from restaurants.models import RestaurantLocation


from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]

    def __init__(self, user=None, *args, **kwargs):
        # print(kwargs.pop('user'))
        print(user)
        # print(kwargs.pop('instance'))
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)#.exclude(item__isnull=False)

skaterapp/menus/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ItemForm
from .models import Item
# Create your views here.

class ItemListView(ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
    form_class = ItemForm
    template_name = 'form.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        # kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
        return kwargs




    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

skaterapp/menus/templates/menus/detail-update.html
{% extends 'base.html' %}
{% block head_title %} Menu Items || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>{{ object.name }}</h1>
    <h3>Location: {{ object.restaurant.name }}</h3>
    {% if object.contents %}
        Contents
        <ul>
            {% for item in object.get_contents %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if object.excludes %}
        Excludes
        <ul>
            {% for item in object.get_excludes %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <hr/>
    <h3>Make Changes</h3>
    {% include 'snippets/form_snippet.html' with form=form %}
{% endblock content %}

skaterapp/menus/templates/menus/item_detail.html
{% extends 'base.html' %}
{% block head_title %} Menu Items || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>{{ object.name }}
        <small>
            <a href="{{ object.get_absolute_url_update }}"> ±Edit</a>
        </small>
    </h1>
    <h3>Location: {{ object.restaurant.name }}</h3>
    {% if object.contents %}
        Contents
        <ul>
            {% for item in object.get_contents %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if object.excludes %}
        Excludes
        <ul>
            {% for item in object.get_excludes %}
                <li>{{ item }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock content %}

skaterapp/menus/templates/menus/item_list.html
{% extends 'base.html' %}
{% block head_title %} Menu Items || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>Menu Items<small><a href="{% url 'menus:create' %}"> +New</a> </small></h1>

    <ul>
        {% for obj in object_list %}
            <li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br/>
                {% if obj.contents %}
                Contents
                <ul>
                    {% for item in obj.get_contents %}
                        <li>{{ item }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                {% if obj.excludes %}
                Excludes
                <ul>
                    {% for item in obj.get_excludes %}
                        <li>{{ item }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </li>
            <li>
            {% empty %}
            <a href="{% url 'menus:create' %}"> Add Menu Item</a>
            </li>

        {% endfor %}
    </ul>
{% endblock content %}