skaterapp/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemUpdateView,
    ItemDetailView,
    ItemCreateView
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

skaterapp/restaurants/urls.py
from django.conf.urls import url

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^$', RestaurantListView.as_view(), name='list'),
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
]

skaterapp/skaterapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView

from profiles.views import ProfileFollowToggle


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profile')),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^anggaran/', include('anggaran.urls', namespace='anggaran')),
]

skaterapp/restaurants/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
    def search(self, query):
        if query :
            query = query.strip()
            return self.filter(
                Q(location__icontains=query)|
                Q(category__icontains=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
    
            ).distinct()
        return self


class RestaurantLocationManager(models.Manager):
    def get_queryset(self):
        return RestaurantLocationQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class RestaurantLocation(models.Model) :
    owner           = models.ForeignKey(User)  # django models unleashed joincfe
    name            = models.CharField(max_length = 120)
    location        = models.CharField(max_length = 120, null = True, blank = True)
    category        = models.CharField(max_length = 120, null = True, blank = True, validators=[validate_category])
    timestamp       = models.DateTimeField(auto_now_add = True)
    updated         = models.DateTimeField(auto_now=True)
    slug            = models.SlugField(unique=True, null=True, blank=True)

    objects = RestaurantLocationManager() # add Model.objects.all()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurants:detail', kwargs={'slug': self.slug})

    def get_absolute_url_update(self):
        return reverse('restaurants:edit', kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def restaurantLocationPreSaveReceiver(sender, instance, *args, **kwargs) :
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


# def restaurantLocationPostSaveReceiver(sender, instance, created, *args, **kwargs) :
#     print('saved')
#     print(instance.timestamp)
#     if not instance.slug:
#         instance.slug = unique_slug_generator(instance)
#         instance.save()


pre_save.connect(restaurantLocationPreSaveReceiver, sender=RestaurantLocation)

# post_save.connect(restaurantLocationPostSaveReceiver, sender=RestaurantLocation)

skaterapp/restaurants/forms.py
from django import forms
from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form) :
    name            = forms.CharField()
    location        = forms.CharField(required=False)
    category        = forms.CharField(required=False)

class RestaurantLocationCreateForm(forms.ModelForm) :
    # email           = forms.EmailField()
    #category          = forms.CharField( required=False, validators=[validate_category])
    class Meta:
        model = RestaurantLocation
        fields = [
            'name',
            'location',
            'category',
        ]
    #
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "Hello":
            raise forms.ValidationError("Your name's not Hello")
        return name

skaterapp/restaurants/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.views import View
from django.views.generic import TemplateView, DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from .models import RestaurantLocation
from .forms import RestaurantLocationCreateForm

class RestaurantListView(LoginRequiredMixin, ListView) :
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

class RestaurantDetailView(DetailView) :
    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView) :
    form_class = RestaurantLocationCreateForm
    template_name = 'form.html'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Add Restaurant'
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView) :
    form_class = RestaurantLocationCreateForm
    template_name = 'restaurants/detail-update.html'

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Edit {}'.format(self.get_object().name)
        return context

    def get_queryset(self):
        return RestaurantLocation.objects.filter(owner=self.request.user)

skaterapp/restaurants/templates/restaurants/detail-update.html
{% extends 'base.html' %}
{% block head_title %} {{ form.instance.title }}Restaurants || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>
        {{ form.instance.title }}
        <small>
            {{ form.instance.category }}
        </small>
    </h1>
    <p>{{ form.instance.location }}</p>
    <p>{{ form.instance.timestamp }}, {{ form.instance.updated|timesince }} ago</p>

    <hr/>
    <h3>Make Changes</h3>
    {% include 'snippets/form_snippet.html' with form=form %}
{% endblock content %}

skaterapp/restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends 'base.html' %}
{% block head_title %} Restaurants || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>
        {{ restaurantlocation.title }}
        <small>
            {{ restaurantlocation.category }}
{#            <a href="{{ object.get_absolute_url_update }}"> | Edit</a>#}
        </small>
    </h1>
    <p>{{ object.location }}</p>
    <p>{{ restaurantlocation.timestamp }}, {{ restaurantlocation.updated|timesince }} ago</p>
{% endblock content %}

skaterapp/restaurants/templates/restaurants/restaurantlocation_list.html
{% extends 'base.html' %}
{% block head_title %} Restaurants || {{ block.super }} {% endblock head_title %}

{%  block content %}
    <h1>My Restaurant<small><a href="{% url 'restaurants:create' %}"> +Add New</a> </small></h1>

    <ul>
        {% for obj in object_list %}
{#            <li><a href="{% url 'restaurant-detail' slug=obj.slug %}">{{ obj.name }}</a></li>#}
            <li><a href="{{ obj.get_absolute_url }}">{{ obj.name }}</a><br/>
            {{ obj.location }} {{ obj.category }} {{ obj.timestamp }}  {{ obj.updated }}
            </li>

            {% empty %}
                <li><a href="{% url 'restaurants:create' %}" >Add One</a></li>

        {% endfor %}
    </ul>
{% endblock content %}